- name: -- Block tasks for ihs start ---
  block:
    - name: -- IHS - Starting --
      become: true
      become_user: web
      shell: |
         /usr/IBMIHS/bin/apachectl -k start
      ignore_errors: true
      register: apache_start_result

    - name: -- IHS - IBMIHS|Web Process Kontrol --
      become: true
      become_user: web
      shell: sleep 10 && ps -ef|grep httpd|grep -v grep|wc -l
      register: ihs_process_controller_again

    - name: -- IHS - 'running' --
      become: true
      become_user: web
      set_fact:
        IHS_status: "RUNNING"
      when:
      - ihs_process_controller_again.stdout != "0"

    - name: -- IHS - Kapalı mı  --
      become: true
      become_user: web
      set_fact:
        IHS_status: "CLOSED"
      when:
      - ihs_process_controller_again.stdout == "0"
